extends: airbnb

parser: babel-eslint

plugins:
  - react-hooks
  - jsx-a11y
  - import
  - prettier

rules:
  react/jsx-filename-extension: 0
  react/jsx-one-expression-per-line: 0
  react/require-default-props: 0
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  prettier/prettier: error
  arrow-parens: 0
  function-paren-newline: 0
  object-curly-newline: 0
  implicit-arrow-linebreak: 0
