extends: airbnb

plugins:
  - react
  - react-hooks
  - jsx-a11y
  - import
  - prettier

rules:
  react/jsx-filename-extension: 0
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  prettier/prettier: error
  arrow-parens: 0
