language: node_js

script:
  - NODE_ENV=production
  - npm run build
  - npm run export

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: out
  on:
    branch: master